# Generated by Django 5.2 on 2025-06-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
