# Generated by Django 5.2 on 2025-05-20 00:59

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0007_delete_prueba_alter_empleado_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='observaciones',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=5432, verbose_name='Texto de Observaciones'),
            preserve_default=False,
        ),
    ]
