# Generated by Django 5.2 on 2025-06-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0009_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_ingreso',
        ),
    ]
