# Generated by Django 5.2 on 2025-06-11 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0010_remove_empleado_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['trabajo'], 'verbose_name': 'Trabajo/Rol', 'verbose_name_plural': 'Trabajos/Roles'},
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='nombreRol',
            new_name='trabajo',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleado.rol', unique=True, verbose_name='Rol/Trabajo'),
        ),
    ]
