# Generated by Django 5.2 on 2025-06-11 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0011_alter_rol_options_rename_nombrerol_rol_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='trabajo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleado.rol', verbose_name='Rol/Trabajo'),
        ),
    ]
