# Generated by Django 5.2 on 2025-06-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0012_alter_empleado_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleado.rol'),
        ),
    ]
