# Generated by Django 5.2 on 2025-06-11 06:07

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0013_alter_empleado_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='habilidadesRol',
            field=models.ManyToManyField(blank=True, to='empleado.habilidades'),
        ),
    ]

